name: todo_app
description: tracko

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter    
  provider: ^6.1.2
  http: ^1.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# إعدادات الأيقونة المعدلة والجاهزة
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/trackoLogo4.png"
  adaptive_icon_foreground: "assets/icons/trackoLogo4.png"
  adaptive_icon_background: "#FFB803"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/